version: '3.7'

services:

  sample:
    container_name: web 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "80:80"
      - "9229:9229"
    environment:
      - CHOKIDAR_USEPOLLING=true